name: 'Action workflow'

on:
  push:
    branches:
      - main

jobs:
  my-custom-action:
    runs-on: ubuntu-latest
    steps:
      - name: Run my action
        uses: mohl-re/test-action@main
      
