name: My test Workflows

on:
  push:
    branches:
      - main
      
jobs:
  linux-job:
    env:
      MYVAR: HELLO
    runs-on: ubuntu-latest
    steps: 
      - name: Linux date
        run: echo $MY_VAR
