name: 'Upload/Download Artifacts'
on:
  push:
    branches:
      main
env:
  ARTIFACT_NAME: 'test.txt'


jobs:
  upload-job-1:
    runs-on: ubuntu-latest
    steps:
    - name: create test file
      run: echo 'test' > $ARTIFACT_NAME
    - name: checkout-code
      uses: actions/checkout@v3
    - name: upload artifact
      uses: action/upload-artifact@v3
      with:
        name: $ARTIFACT_NAME
  download-job2:
    runs-on: ubuntu-latest
    needs: upload-job-1
    steps:
      - name: download-artifact
        uses: action/download-artifact@v3
        with:
          name: $ARTIFACT_NAME
