name: concurency

on:
  workflow_dispatch:

concurrency:
  group: concurent
  cancel-in-progress: true

jobs:
  concurent-job:
    runs-on: ubuntu-latest
    steps:
      - name: Do an LS
        run: ls
