name: needs

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: action/checkout@v4
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: echo
        run: echo test
