name: needs

on:
  workflow_dispatch:

jobs:
  job1:
    outputs:
      test-output: ${{ steps.output-id.outputs.test }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: job1-id
        uses: actions/checkout@v4
      - name: output
        id: output-id
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: echo output from job1
        run: echo ${{ needs.job1.outputs.test-output }}
