name: needs

on:
  push:

jobs:  
  job1:
    runs-on: ubuntu-latest
    steps:
      - run:          echo test
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  job3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - run: echo job3
