name: Python workflow

on:
  push:
    branches:
      - main

jobs:
  python-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
      - name: create python file
        run: echo 'print("hello world")' > hello.py
      - name: run python script
        run: python hello.py

  next-job:
    runs-on: ubuntu-latest
    needs: python-job
    if: success()
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: create dumb file
        run: echo 'test' > test.txt
      - name: create artifact
        uses: actions/upload-artifact@v4
        with:
          name: python.yml
          path: ./github/workflows/
