name: release

on:
  push:
    branches:
      main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: create release
        uses: actions/create-release@main
        with:
          tag_name: 1.0.0
          release_name: "1.0.0"
          body: "my first release"
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
