name: service-wf

on:
  workflow_dispatch:

env:
  image_name: 'node:latest'

jobs:
  job1:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out
        uses: actions/checkout@v4
      - name: Echo var
        run: echo ${{ vars.MY_VAR }}
  service-job:
    runs-on: ubuntu-latest
    needs: job1
    container:
      image: $image_name
      env:
        NODE_ENV: dev
      ports:
        - 80
      volumes:
        - volume/volume_mount
      options:
        --cpus 1
    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
    steps:
      - uses: actions/checkout@v4
