name: service-wf

on:
  workflow_dispatch:

env:
  image_name: 'node:10.16-jessie'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out
        uses: actions/checkout@v4
      - name: Echo var
        run: echo ${{ vars.MY_VAR }}
  service-job:
    runs-on: ubuntu-latest
    needs: job1
    container:
      image: ${{ env.image_name }}
      env:
        NODE_ENV: dev
      ports:
        - 80
      volumes:
        - volume/volume_mount
      options:
        --cpus 1
    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
