name: stale

on:
  push:
    branches:
      - main

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
