name: 'Test workflow run'

on:
  workflow_run:
    workflows: [Test Organization Secrets]
    types:
      - completed

jobs:
  test-wf-run:
    runs-on: ubuntu-latest
    steps:
      - name: 'Do something'
        run: |
          echo "This workflow ran after another one"  
